Repository dimagi/commcare-cloud, pull requests merged in 2020-10, with the labels that each got.

#4291 fix service checks for postgresql / citus + changelog
  changelog/0038-update-postgresql-monit-conf.yml
  docs/changelog/0038-update-postgresql-monit-conf.md
  docs/changelog/index.md
  src/commcare_cloud/commands/ansible/service.py
Labels: bug

#4292 'new-changelog' command to create an templated changelog
  changelog/README.md
  src/commcare_cloud/manage_commcare_cloud/changelog-template.yml.j2
  src/commcare_cloud/manage_commcare_cloud/make_changelog.py
  src/commcare_cloud/manage_commcare_cloud/manage_commcare_cloud.py
Labels: enhancement

#4300 allow passing IGNORE_ALL_DEMO_USER_SUBMISSIONS
  src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Labels: Open for review: do not merge

#4297 allow passing USE_PHONE_ENTRIES
  src/commcare_cloud/ansible/roles/commcarehq/templates/localsettings.py.j2
Labels: Open for review: do not merge
